"""
Firebase Storage abstraction.

This module NEVER pretends to have real Firebase credentials. If
FIREBASE_PROJECT_ID / FIREBASE_CLIENT_EMAIL / FIREBASE_PRIVATE_KEY /
FIREBASE_STORAGE_BUCKET are not all present in the environment, it falls
back to writing under `local_storage_fallback_dir` on local disk so the
rest of the API keeps working during development. That fallback is
clearly logged and MUST NOT be used in production — see README.md.

Every storage key handed to `upload_bytes` is generated by
`generate_object_key` below, server-side, from validated identifiers
(cooperativa_id / entity / entity_id) — never from a client-supplied
filename or path, which closes off path traversal entirely.
"""
from __future__ import annotations

import logging
import os
import uuid
from pathlib import Path

from app.core.config import get_settings

logger = logging.getLogger("beetticket.storage")

settings = get_settings()

_firebase_bucket = None
_firebase_init_attempted = False


def _firebase_configured() -> bool:
    return bool(
        settings.firebase_project_id
        and settings.firebase_client_email
        and settings.firebase_private_key
        and settings.firebase_storage_bucket
    )


def _get_firebase_bucket():
    """Lazily initializes the Firebase Admin SDK exactly once, using only
    environment-provided credentials. Returns None (never raises) if
    Firebase isn't configured, so callers fall back to local disk."""
    global _firebase_bucket, _firebase_init_attempted
    if _firebase_bucket is not None or _firebase_init_attempted:
        return _firebase_bucket
    _firebase_init_attempted = True

    if not _firebase_configured():
        logger.warning(
            "Firebase Storage no está configurado (faltan variables de entorno). "
            "Usando almacenamiento local de desarrollo en '%s'. Esto NO debe usarse en producción.",
            settings.local_storage_fallback_dir,
        )
        return None

    try:
        import firebase_admin
        from firebase_admin import credentials, storage

        cred_dict = {
            "type": "service_account",
            "project_id": settings.firebase_project_id,
            "client_email": settings.firebase_client_email,
            # Real deployments store the key with literal "\n" escapes in
            # the env var; this restores real newlines without ever
            # logging or hardcoding the key itself.
            "private_key": settings.firebase_private_key.replace("\\n", "\n"),
            "token_uri": "https://oauth2.googleapis.com/token",
        }
        cred = credentials.Certificate(cred_dict)
        if not firebase_admin._apps:
            firebase_admin.initialize_app(cred, {"storageBucket": settings.firebase_storage_bucket})
        _firebase_bucket = storage.bucket()
        return _firebase_bucket
    except Exception:
        logger.exception("No se pudo inicializar Firebase Storage; usando almacenamiento local de desarrollo.")
        return None


def generate_object_key(prefix: str, cooperativa_id: int, entidad: str, entidad_id: int, extension: str) -> str:
    """Server-generated storage key. `extension` must include the leading
    dot (e.g. '.pdf') and is expected to already be validated upstream."""
    return f"{prefix}/{cooperativa_id}/{entidad}/{entidad_id}/{uuid.uuid4().hex}{extension}"


def upload_bytes(object_key: str, data: bytes, content_type: str) -> str:
    """Uploads `data` and returns the stored reference (the object key
    itself — callers persist this string in PostgreSQL, never the raw
    bytes and never a filesystem-specific absolute path)."""
    bucket = _get_firebase_bucket()
    if bucket is not None:
        blob = bucket.blob(object_key)
        blob.upload_from_string(data, content_type=content_type)
        return object_key

    # --- local dev fallback ---
    local_path = Path(settings.local_storage_fallback_dir) / object_key
    local_path.parent.mkdir(parents=True, exist_ok=True)
    local_path.write_bytes(data)
    return object_key


def get_signed_download_reference(object_key: str, expires_in_seconds: int = 300) -> str:
    """Returns a reference the affiliate/admin frontend can use to fetch
    the file. With real Firebase configured this is a short-lived signed
    URL; in the local dev fallback it's a path under the API's own
    download endpoint. Either way the caller never receives a raw,
    permanent, unauthenticated storage path.

    NOT currently used by any mounted route — every download endpoint in
    this phase (routers/tickets.py) reads bytes via `download_bytes`
    below and streams them directly in an already ownership-verified
    response, rather than redirecting to a second, separately-secured
    route. Kept for a future pass that wants a real signed-URL flow."""
    bucket = _get_firebase_bucket()
    if bucket is not None:
        blob = bucket.blob(object_key)
        return blob.generate_signed_url(expiration=expires_in_seconds)
    return f"/api/archivos/local/{object_key}"


def download_bytes(object_key: str) -> bytes | None:
    """Reads back the bytes for `object_key` — from Firebase if
    configured, otherwise from local disk. Returns None if the object
    doesn't exist. Callers MUST have already verified the requester owns
    this object before calling this — there is no per-object ACL here."""
    bucket = _get_firebase_bucket()
    if bucket is not None:
        blob = bucket.blob(object_key)
        if not blob.exists():
            return None
        return blob.download_as_bytes()
    return read_local_fallback(object_key)


def delete_object(object_key: str) -> None:
    """Used by `routers/plantillas.py`'s `DELETE /{plantilla_id}` (removes
    the stored HTML/config alongside the DB row) and reserved for the
    future scheduled retention job (§24)."""
    bucket = _get_firebase_bucket()
    if bucket is not None:
        bucket.blob(object_key).delete()
        return
    local_path = Path(settings.local_storage_fallback_dir) / object_key
    if local_path.exists():
        os.remove(local_path)


def read_local_fallback(object_key: str) -> bytes | None:
    """Only meaningful in local-dev-fallback mode; used by the
    dev-only download endpoint so the flow is testable without real
    Firebase credentials. Never used when Firebase is actually configured."""
    local_path = Path(settings.local_storage_fallback_dir) / object_key
    if not local_path.exists():
        return None
    return local_path.read_bytes()
